### ISSUE TITLE
Classifier for HuggingFace ccnews

### ISSUE THREAD

**Issue by uokesita** [AnthusAI/Plexus#8]
@endymion 
Can this be a good issue to work on to start with Plexus?
https://huggingface.co/datasets/stanford-oval/ccnews

Is there a similar classifier in Plexus I can have a look at?

**Comment by endymion** [comment]
Yes, that one looks better than the other news-based one that I was looking at because the category classifications in this one are strings.  The other one used numbers as indexes, and that would make things more complicated and a little less fun.

This one has some weird category names: "Scottish News".

But that seems okay.
